package Personal;

import General.menuMatricula;
import javax.swing.*;
import org.w3c.dom.Node;
import java.lang.reflect.Field;
import General.*;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Random;
import General.MetosAlumnos;

/**
 *
 * @author Lenovo
 */
public class agregarM extends javax.swing.JFrame {

    Nodo cabeza;
    Nodo ultimo;
    Random randi = new Random();
    
    
    /**
     * Creates new form agregarM
     */
    public agregarM() {
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        ultimo = null;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameIngre = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        numIngre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        apellidoIngre1 = new javax.swing.JTextField();
        BtnIngreso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        avisoSN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setForeground(new java.awt.Color(51, 0, 102));

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("      Agregar a la lista");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nameIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameIngreActionPerformed(evt);
            }
        });
        nameIngre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameIngreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameIngreKeyTyped(evt);
            }
        });

        btnSiguiente.setForeground(new java.awt.Color(0, 0, 0));
        btnSiguiente.setText("Cerrar");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        numIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numIngreActionPerformed(evt);
            }
        });
        numIngre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numIngreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numIngreKeyTyped(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese la nota del estudiante:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingrese el apellido:");

        apellidoIngre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoIngre1ActionPerformed(evt);
            }
        });
        apellidoIngre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                apellidoIngre1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoIngre1KeyTyped(evt);
            }
        });

        BtnIngreso.setForeground(new java.awt.Color(0, 0, 0));
        BtnIngreso.setText("Ingresar");
        BtnIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnIngresoMouseClicked(evt);
            }
        });
        BtnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresoActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese el nombre:");

        avisoSN.setForeground(new java.awt.Color(255, 255, 255));
        avisoSN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))))
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avisoSN, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nameIngre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(apellidoIngre1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(numIngre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameIngre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(apellidoIngre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numIngre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addComponent(BtnIngreso)
                .addGap(31, 31, 31)
                .addComponent(avisoSN, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSiguiente)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void keyTyped(KeyEvent e) {
        char c = e.getKeyChar();
        if (!Character.isLetter(c)) {
            e.consume(); // Deshabilitar evento keyTyped
        }

    }

    public void keyTypedNums(KeyEvent e) {
        char c = e.getKeyChar();
        if (!Character.isDigit(c)) {
            e.consume(); // Deshabilitar evento keyTyped
        }
    }

    public void HabilitarBoton() {

        if (!nameIngre.getText().isEmpty() && !apellidoIngre1.getText().isEmpty() && !numIngre.getText().isEmpty()) {
            BtnIngreso.setEnabled(true);
        } else {
            BtnIngreso.setEnabled(false);
        }
    }
    public pilas pila = new pilas();
    private void BtnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresoActionPerformed
       JOptionPane.showMessageDialog(null, "Cargando...");
        
        String nombreIngre = nameIngre.getText();
        String apellidoIngre = apellidoIngre1.getText();
        int notaIngre = Integer.parseInt(numIngre.getText());
        String fullName= nombreIngre+ " " +apellidoIngre;
        MetosAlumnos.ingresarDatos(fullName, notaIngre);
        MetosAlumnos.mostrarLista();
        
        // Validar los datos de entrada
        if (nombreIngre.isEmpty() ||apellidoIngre.isEmpty() || notaIngre < 0 || notaIngre > 100) {
        JOptionPane.showMessageDialog(null, "Error: los datos ingresados no son válidos");
        return;
        }   
    
        // Insertar los datos en la pila
        
        for (int i = 0; i < nombreIngre.length(); i++) {
        int n = randi.nextInt(999) + 1;
        pila.insertar(notaIngre, n, fullName);
            
        }
        
        // Limpiar los campos de entrada
        nameIngre.setText("");
        apellidoIngre1.setText("");
        numIngre.setText("");
    
//        // Mostrar la pila en la consola
        
    
    }//GEN-LAST:event_BtnIngresoActionPerformed

    private void numIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numIngreActionPerformed

    }//GEN-LAST:event_numIngreActionPerformed

    private void BtnIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIngresoMouseClicked

    }//GEN-LAST:event_BtnIngresoMouseClicked

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        menuMatricula mn = new menuMatricula();
        setVisible(false);
        mn.setVisible(true);
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void nameIngreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameIngreKeyReleased
        HabilitarBoton();
    }//GEN-LAST:event_nameIngreKeyReleased

    private void numIngreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numIngreKeyReleased
        HabilitarBoton();
    }//GEN-LAST:event_numIngreKeyReleased

    private void numIngreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numIngreKeyTyped

        keyTypedNums(evt);
        if (numIngre.getText().length() > 2) {
            evt.consume();

        }

    }//GEN-LAST:event_numIngreKeyTyped

    private void nameIngreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameIngreKeyTyped
        keyTyped(evt);
        if (nameIngre.getText().length() > 18) {
            evt.consume();

        }
    }//GEN-LAST:event_nameIngreKeyTyped

    private void nameIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameIngreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameIngreActionPerformed

    private void apellidoIngre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoIngre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoIngre1ActionPerformed

    private void apellidoIngre1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoIngre1KeyReleased
       
        HabilitarBoton();
    }//GEN-LAST:event_apellidoIngre1KeyReleased

    private void apellidoIngre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoIngre1KeyTyped
      
       keyTyped(evt);
        if (apellidoIngre1.getText().length() > 18) {
            evt.consume();

        }
    }//GEN-LAST:event_apellidoIngre1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarM().setVisible(true);
            }
        });
    }

//    MetosAlumnos pila = new MetosAlumnos();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngreso;
    private javax.swing.JTextField apellidoIngre1;
    private javax.swing.JLabel avisoSN;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameIngre;
    private javax.swing.JTextField numIngre;
    // End of variables declaration//GEN-END:variables
}
