/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package General;

import javax.swing.ImageIcon;

/**
 *
 * @author Lenovo
 */
public class filtro extends javax.swing.JFrame {

    /**
     * Creates new form filtro
     */
    public filtro() {
        setUndecorated(true);
        initComponents();
        
        siguienteContraseña.setIcon(new ImageIcon(getClass().getResource("/Imagenes/candadocerrrado.png")));;
        siguienteContraseña.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        siguienteContraseña = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        contraseñaIngreso = new javax.swing.JTextField();
        mensajeContraseña = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        siguienteContraseña.setBackground(new java.awt.Color(153, 255, 255));
        siguienteContraseña.setForeground(new java.awt.Color(0, 0, 0));
        siguienteContraseña.setText("Siguiente");
        siguienteContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(siguienteContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 250, 130, 44));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese la contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 47, -1, -1));

        contraseñaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaIngresoActionPerformed(evt);
            }
        });
        getContentPane().add(contraseñaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 44, 132, -1));

        mensajeContraseña.setForeground(new java.awt.Color(255, 255, 255));
        mensajeContraseña.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(mensajeContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 91, 132, 28));

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Verificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 96, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void siguienteContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteContraseñaActionPerformed
        //Boton siguiente
        menuMatricula AbrirServer = new menuMatricula();
        dispose();
        AbrirServer.setVisible(true);

        //
    }//GEN-LAST:event_siguienteContraseñaActionPerformed

    private void contraseñaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaIngresoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ImageIcon icono2 = new ImageIcon("/Imagenes/candadoabierto.png");
       
        boolean confirmacionPassword;
        String Contraseña = "1234";

        String contraseña1 = contraseñaIngreso.getText();
        if (contraseña1.equals(Contraseña)) {
            confirmacionPassword = true;
            mensajeContraseña.setText("Bienvenido!");
            siguienteContraseña.setEnabled(true);
            siguienteContraseña.setIcon(new ImageIcon(getClass().getResource("/Imagenes/candadoabierto.png")));

        } else {

            mensajeContraseña.setText("Acceso denegado!");
            siguienteContraseña.setEnabled(false);
            siguienteContraseña.setIcon(new ImageIcon(getClass().getResource("/Imagenes/candadocerrrado.png")));;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(filtro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(filtro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(filtro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(filtro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new filtro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contraseñaIngreso;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mensajeContraseña;
    private javax.swing.JButton siguienteContraseña;
    // End of variables declaration//GEN-END:variables
}
